"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import dj_database_url

from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
# Read .env file from the same directory as settings.py (a_core/.env)
env.read_env(Path(__file__).parent / '.env')




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

DEBUG = False  # Temporarily enabled to see error details
    

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['herbiesplace.be','websiteherbiesplace-production.up.railway.app','localhost', '127.0.0.1', '*']

CSRF_TRUSTED_ORIGINS = [ 'https://herbiesplace.be','https://websiteherbiesplace-production.up.railway.app' ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'django_htmx',
    'whitenoise.runserver_nostatic',
    'anymail',
    'a_home',
    'a_users',
    'a_portfolio',
    'a_share',
     
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'portfolio'

ROOT_URLCONF = 'a_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'a_users.context_processors.unread_messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'a_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use DATABASE_URL if provided (Railway public connection), otherwise use SQLite for local development
DATABASE_URL = env('DATABASE_URL', default=None)

# Check if DATABASE_URL contains internal Railway hostname (not accessible from local machine)
if DATABASE_URL and 'railway.internal' in DATABASE_URL:
    # Reject internal Railway URLs - they only work inside Railway's network
    print("WARNING: DATABASE_URL contains 'railway.internal' which is not accessible from your local machine.")
    print("Please use the PUBLIC connection URL from Railway (hostname like 'containers-xxx.railway.app')")
    print("Falling back to SQLite for local development.")
    DATABASE_URL = None

if DATABASE_URL:
    # Parse the full database URL (Railway provides this as a public connection string)
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Check individual DB settings, but reject if they use internal hostname
    db_host = env('DB_HOST', default=None)
    if db_host and 'railway.internal' in db_host:
        print("WARNING: DB_HOST contains 'railway.internal' which is not accessible from your local machine.")
        print("Please use the PUBLIC connection URL from Railway or set DATABASE_URL with public hostname.")
        print("Falling back to SQLite for local development.")
        db_host = None
    
    if db_host:
        # Use individual DB settings (only if host is public)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env('DB_NAME'),
                'USER': env('DB_USER'),
                'PASSWORD': env('DB_PASSWORD'),
                'HOST': db_host,
                'PORT': env('DB_PORT'),
            }
        }
    else:
        # Use SQLite for local development when no database is configured
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / 'static' ]

#whitenoise static stuff
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'

AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default=None)
AWS_ACCESS_KEY_ID = env("SPACES_KEY", default=None)
AWS_SECRET_ACCESS_KEY = env("SPACES_SECRET", default=None)
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default=None)
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400',}
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None  # Use bucket default ACL

# Media files configuration (custom storage class)
# Django 5.1+ uses STORAGES dictionary, but DEFAULT_FILE_STORAGE still works for backward compatibility
# Only use S3 storage if credentials are provided, otherwise fall back to local
if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_S3_ENDPOINT_URL:
    # Ensure endpoint URL has https:// protocol for boto3
    endpoint = AWS_S3_ENDPOINT_URL
    if not endpoint.startswith('http://') and not endpoint.startswith('https://'):
        endpoint = f'https://{endpoint}'
    
    # For MEDIA_URL, use the bucket subdomain format
    endpoint_domain = endpoint.replace('https://', '').replace('http://', '')
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{endpoint_domain}/media/'
    
    # Set the endpoint URL for boto3 (must include https://)
    AWS_S3_ENDPOINT_URL = endpoint
    
    # Don't set MEDIA_ROOT when using S3 storage
    MEDIA_ROOT = None
    
    # Also set DEFAULT_FILE_STORAGE for backward compatibility
    DEFAULT_FILE_STORAGE = 'a_core.storage_backends.MediaStorage'
    
    print(f"✓ DigitalOcean Spaces configured: {MEDIA_URL}")
    print(f"  Bucket: {AWS_STORAGE_BUCKET_NAME}, Endpoint: {AWS_S3_ENDPOINT_URL}")
    print(f"  Storage: {DEFAULT_FILE_STORAGE}")
else:
    # Fall back to local storage if S3 credentials are not configured
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    
    print("⚠ WARNING: DigitalOcean Spaces not configured - using local storage")
    print(f"  Missing: AWS_STORAGE_BUCKET_NAME={AWS_STORAGE_BUCKET_NAME is not None}, "
          f"SPACES_KEY={AWS_ACCESS_KEY_ID is not None}, "
          f"SPACES_SECRET={AWS_SECRET_ACCESS_KEY is not None}, "
          f"AWS_S3_ENDPOINT_URL={AWS_S3_ENDPOINT_URL is not None}")
    print(f"  Using: {DEFAULT_FILE_STORAGE}")
    print("  Check your a_core/.env file has all required variables.")

# For Django 5.1+, define STORAGES dictionary after determining which storage to use
STORAGES = {
    'default': {
        'BACKEND': DEFAULT_FILE_STORAGE,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

#MEDIA_URL = 'media/'

#MEDIA_ROOT = BASE_DIR / 'media'

# CDN URL for serving files
# STATIC_URL = 'https://test-website.nyc3.cdn.digitaloceanspaces.com/static/'
# MEDIA_URL = 'https://website-herbiesplace.ams3.digitaloceanspaces.com/media/'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Maximum file size for photo uploads (in bytes)
MAX_PHOTO_SIZE = 10 * 1024 * 1024  # 10 MB 

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = "{% url 'account_signup' %}?next={% url 'profile-onboarding' %}"

 

# For development, you can use console backend to see emails in terminal
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#email using anymail and Brevo provider
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"

ANYMAIL = {
    'BREVO_API_KEY': env('BREVO_API_KEY'),
}
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_FORMS = {
    'signup': 'a_users.adapters.CustomSignupForm',
}
ACCOUNT_USERNAME_BLACKLIST = ['debaas','admin', 'root', 'superuser', 'superadmin', 'superuseradmin', 'superadminadmin', 'superuseradminadmin']
